
<?php $All = array('http://www.reed.co.uk/jobs/rss/edinburgh?source=rss','http://www.indeed.co.uk/rss?q=&l=edinburgh','http://www.jobstoday.co.uk/jobsrss/?LocationId=2170&countrycode=GB','http://www.scotcareers.co.uk/jobsrss/?LocationId=2170%2c20752050%2c20752010&radiallocation=5&countrycode=GB','http://www.fish4.co.uk/jobsrss/?LocationId=2170&countrycode=GB','https://jobs.theguardian.com/jobsrss/?LocationId=2170&radiallocation=10&countrycode=GB');
$Engineering=array('http://www.reed.co.uk/jobs/rss/engineering/edinburgh?source=rss','http://www.indeed.co.uk/rss?q=engineering&l=Edinburgh','http://www.jobstoday.co.uk/jobsrss/?Sector=3&LocationId=2170&countrycode=GB','http://www.scotcareers.co.uk/jobsrss/?Sectors=54&LocationId=2170%2c20752050%2c20752010&radiallocation=5&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=54&LocationId=2170&countrycode=GB');
$Catering = array('http://www.reed.co.uk/jobs/rss/hospitality-catering/edinburgh?source=rss','http://www.indeed.co.uk/rss?q=catering&l=edinburgh','http://www.jobstoday.co.uk/jobsrss/?Sector=513020&LocationId=2170&countrycode=GB','http://www.scotcareers.co.uk/jobsrss/?Sectors=8&LocationId=2170%2c20752050%2c20752010&radiallocation=5&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=8&LocationId=2170&countrycode=GB');
$IT = array('http://www.reed.co.uk/jobs/rss/$rss/edinburgh?source=rss',
'http://www.scotcareers.co.uk/jobsrss/?Sectors=104&LocationId=2170&countrycode=GB','http://www.indeed.co.uk/rss?q=IT+engineer&l=Edinburgh','http://www.jobstoday.co.uk/jobsrss/?Sector=13&LocationId=2170&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=104&LocationId=2170&countrycode=GB');
$Sales=array('http://www.reed.co.uk/jobs/rss/sales/edinburgh?source=rss','http://www.scotcareers.co.uk/jobsrss/?Sectors=128&LocationId=2170&countrycode=GB',
'http://www.indeed.co.uk/rss?q=sales&l=Edinburgh','http://www.jobstoday.co.uk/jobsrss/?Sector=28&LocationId=2170&keywords=sales&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=128&LocationId=2170&countrycode=GB','https://jobs.theguardian.com/jobsrss/?JobFunction=15&LocationId=2170&radiallocation=10&countrycode=GB');
$Finance=array('http://www.reed.co.uk/jobs/rss/financial-services/edinburgh?source=rss','http://www.reed.co.uk/jobs/rss/accountancy/edinburgh?source=rss','http://www.scotcareers.co.uk/jobsrss/?Sectors=1&LocationId=2170&countrycode=GB','http://www.indeed.co.uk/rss?q=finance&l=Edinburgh','http://www.jobstoday.co.uk/jobsrss/?Sector=513011&LocationId=2170&countrycode=GB','http://www.jobstoday.co.uk/jobsrss/?Sector=513016&LocationId=2170&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=6&LocationId=2170&countrycode=GB','http://www.fish4.co.uk/jobsrss/?Sectors=1&LocationId=2170&countrycode=GB','https://jobs.theguardian.com/jobsrss/?JobFunction=10&LocationId=2170&radiallocation=10&countrycode=GB');
$Education=array('http://www.reed.co.uk/jobs/rss/education/edinburgh?source=rss','http://www.jobstoday.co.uk/jobsrss/?Sector=513027&LocationId=2170&countrycode=GB','http://www.scotcareers.co.uk/jobsrss/?Sectors=39&LocationId=2170%2c20752050%2c20752010&radiallocation=5&countrycode=GB','http://www.indeed.co.uk/rss?q=education&l=Edinburgh','http://www.fish4.co.uk/jobsrss/?Sectors=39&LocationId=2170&countrycode=GB');?>